/**
 * Stable keys for mst_smtp_template.template_type (admin / reseller UI) and default fallbacks.
 * Use these strings when inserting rows in Hasura so DB overrides match code.
 *
 * Variables: see TEMPLATE_VARIABLES (documentation for editors / seed scripts).
 */
export const TEMPLATE_TYPE = {
  ADMIN_EMAIL_VERIFICATION_OTP: "admin_email_verification_otp",
  CUSTOMER_EMAIL_VERIFICATION_OTP: "customer_email_verification_otp",
  ADMIN_KYC_SUBMITTED_SUPER: "admin_kyc_submitted_super",
  ADMIN_KYC_APPROVED: "admin_kyc_approved",
  ADMIN_KYC_REJECTED: "admin_kyc_rejected",
  ADMIN_ACCOUNT_DEACTIVATED: "admin_account_deactivated",
  /** Admin suspended reseller (suspended_at set); includes suspension_reason */
  RESELLER_ACCOUNT_SUSPENDED: "reseller_account_suspended",
  CUSTOMER_KYC_SUBMITTED_ADMIN: "customer_kyc_submitted_admin",
  CUSTOMER_KYC_APPROVED: "customer_kyc_approved",
  CUSTOMER_KYC_REJECTED: "customer_kyc_rejected",
  PAYMENT_LINK_GENERATED: "payment_link_generated",
  PAYMENT_SUCCESS_CUSTOMER: "payment_success_customer",
  PAYMENT_SUCCESS_ADMIN: "payment_success_admin",
  PAYMENT_FAILED: "payment_failed",
  NUMBER_ACTIVATED_CUSTOMER: "number_activated_customer",
  CALL_FORWARD_UPDATED: "call_forward_updated",
  NUMBER_SUSPENDED: "number_suspended",
  EXPIRY_REMINDER_30D: "expiry_reminder_30d",
  EXPIRY_REMINDER_15D: "expiry_reminder_15d",
  EXPIRY_REMINDER_7D: "expiry_reminder_7d",
  LOW_WALLET_BALANCE: "low_wallet_balance",
  WALLET_CREDIT_APPROVED: "wallet_credit_approved",
  WALLET_DEBIT_ACTIVATION: "wallet_debit_activation",
  WALLET_DEBIT_RENEWAL: "wallet_debit_renewal",
  WALLET_TOPUP_REQUEST_SUPER: "wallet_topup_request_super",
  WALLET_TOPUP_APPROVED: "wallet_topup_approved",
  WALLET_TOPUP_REJECTED: "wallet_topup_rejected",
  NEW_LOGIN_DETECTED: "new_login_detected",
  MAINTENANCE_ENABLED_ADMIN: "maintenance_enabled_admin",
  MAINTENANCE_DISABLED_ADMIN: "maintenance_disabled_admin",
  PAYMENT_LINK_RESENT: "payment_link_resent",
  PAYMENT_FAILED_ADMIN: "payment_failed_admin",
  RENEWAL_PAYMENT_SUCCESS_CUSTOMER: "renewal_payment_success_customer",
  RENEWAL_PAYMENT_SUCCESS_ADMIN: "renewal_payment_success_admin",
  RENEWAL_PAYMENT_FAILED_CUSTOMER: "renewal_payment_failed_customer",
  RENEWAL_PAYMENT_FAILED_ADMIN: "renewal_payment_failed_admin",
  OFFLINE_PAYMENT_APPROVED_CUSTOMER: "offline_payment_approved_customer",
  OFFLINE_PAYMENT_APPROVED_ADMIN: "offline_payment_approved_admin",
  NUMBER_ACTIVATED_ADMIN: "number_activated_admin",
  CALL_FORWARD_UPDATED_ADMIN: "call_forward_updated_admin",
  NUMBER_SUSPENDED_ADMIN: "number_suspended_admin",
  TELECOM_SUSPENSION_SUPER: "telecom_suspension_super",
};

/**
 * Expected placeholder names in subject/body ({{snake_case}}).
 * Single braces in spec like {User} are normalized to {{user}} in default templates.
 *
 * Additionally, resolveTransactionalEmail may inject (not always present):
 * - brand_logo_url — when context.resellerId is set and the reseller has logo/minified_logo
 *   (requires PUBLIC_API_BASE_URL for filename storage; or absolute http(s) URL as stored)
 * - platform_logo_url — when there is no resellerId and env PLATFORM_LOGO_URL is set
 *   (e.g. admin email OTP header). Example value:
 *   https://app.virtualnumberindia.in/assets/images/own/dlogo.png
 * - customer_display_name — when context.customerId is set (first+last, else profile_name, else email)
 * Custom mst_smtp_template.body HTML may use e.g. <img src="{{brand_logo_url}}" alt="{{brand_name}}" />.
 */
export const TEMPLATE_VARIABLES = {
  [TEMPLATE_TYPE.ADMIN_EMAIL_VERIFICATION_OTP]: [
    "user",
    "otp",
    "expiry_time",
    "support_number",
    "support_email",
    "platform_name",
  ],
  [TEMPLATE_TYPE.CUSTOMER_EMAIL_VERIFICATION_OTP]: [
    "user",
    "otp",
    "expiry_time",
    "support_number",
    "support_email",
    "brand_name",
  ],
  [TEMPLATE_TYPE.ADMIN_KYC_SUBMITTED_SUPER]: ["user", "email", "platform_name"],
  [TEMPLATE_TYPE.ADMIN_KYC_APPROVED]: ["user", "platform_name"],
  [TEMPLATE_TYPE.ADMIN_KYC_REJECTED]: [
    "user",
    "rejection_reason",
    "support_number",
    "support_email",
    "platform_name",
  ],
  [TEMPLATE_TYPE.ADMIN_ACCOUNT_DEACTIVATED]: [
    "user",
    "support_number",
    "support_email",
    "platform_name",
  ],
  [TEMPLATE_TYPE.RESELLER_ACCOUNT_SUSPENDED]: [
    "user",
    "suspension_reason",
    "support_number",
    "support_email",
    "platform_name",
  ],
  [TEMPLATE_TYPE.CUSTOMER_KYC_SUBMITTED_ADMIN]: [
    "user",
    "customer_name",
    "customer_email",
    "brand_name",
  ],
  [TEMPLATE_TYPE.CUSTOMER_KYC_APPROVED]: [
    "user",
    "admin_phone",
    "admin_email",
    "reseller_number",
    "reseller_email",
    "support_number",
    "support_email",
    "brand_name",
  ],
  [TEMPLATE_TYPE.CUSTOMER_KYC_REJECTED]: [
    "user",
    "rejection_reason",
    "support_number",
    "support_email",
    "brand_name",
  ],
  [TEMPLATE_TYPE.PAYMENT_LINK_GENERATED]: [
    "user",
    "payment_link",
    "support_number",
    "support_email",
    "brand_name",
  ],
  [TEMPLATE_TYPE.PAYMENT_SUCCESS_CUSTOMER]: [
    "user",
    "amount",
    "transaction_id",
    "brand_name",
  ],
  [TEMPLATE_TYPE.PAYMENT_SUCCESS_ADMIN]: [
    "user",
    "customer_name",
    "amount",
    "brand_name",
  ],
  [TEMPLATE_TYPE.PAYMENT_FAILED]: [
    "user",
    "support_number",
    "support_email",
    "brand_name",
  ],
  [TEMPLATE_TYPE.NUMBER_ACTIVATED_CUSTOMER]: [
    "user",
    "virtual_number",
    "forward_number",
    "start_date",
    "end_date",
    "brand_name",
  ],
  [TEMPLATE_TYPE.CALL_FORWARD_UPDATED]: ["user", "forward_number", "brand_name"],
  [TEMPLATE_TYPE.NUMBER_SUSPENDED]: [
    "user",
    "virtual_number",
    "support_number",
    "brand_name",
  ],
  [TEMPLATE_TYPE.EXPIRY_REMINDER_30D]: ["user", "virtual_number", "brand_name"],
  [TEMPLATE_TYPE.EXPIRY_REMINDER_15D]: ["user", "virtual_number", "brand_name"],
  [TEMPLATE_TYPE.EXPIRY_REMINDER_7D]: ["user", "virtual_number", "brand_name"],
  [TEMPLATE_TYPE.LOW_WALLET_BALANCE]: ["user", "platform_name", "balance", "threshold"],
  [TEMPLATE_TYPE.WALLET_CREDIT_APPROVED]: ["user", "amount", "date", "platform_name"],
  [TEMPLATE_TYPE.WALLET_DEBIT_ACTIVATION]: [
    "user",
    "amount",
    "balance_after",
    "brand_name",
  ],
  [TEMPLATE_TYPE.WALLET_DEBIT_RENEWAL]: [
    "user",
    "amount",
    "balance_after",
    "brand_name",
  ],
  [TEMPLATE_TYPE.WALLET_TOPUP_REQUEST_SUPER]: [
    "user",
    "amount",
    "reseller_name",
    "platform_name",
  ],
  [TEMPLATE_TYPE.WALLET_TOPUP_APPROVED]: ["user", "amount", "platform_name"],
  [TEMPLATE_TYPE.WALLET_TOPUP_REJECTED]: ["user", "reason", "platform_name"],
  [TEMPLATE_TYPE.NEW_LOGIN_DETECTED]: [
    "user",
    "ip_address",
    "location",
    "support_number",
    "brand_name",
  ],
  [TEMPLATE_TYPE.MAINTENANCE_ENABLED_ADMIN]: ["user", "platform_name"],
  [TEMPLATE_TYPE.MAINTENANCE_DISABLED_ADMIN]: ["user", "platform_name"],
  [TEMPLATE_TYPE.PAYMENT_LINK_RESENT]: [
    "user",
    "payment_link",
    "support_number",
    "support_email",
    "brand_name",
  ],
  [TEMPLATE_TYPE.PAYMENT_FAILED_ADMIN]: [
    "user",
    "customer_name",
    "amount",
    "failure_reason",
    "brand_name",
  ],
  [TEMPLATE_TYPE.RENEWAL_PAYMENT_SUCCESS_CUSTOMER]: [
    "user",
    "amount",
    "transaction_id",
    "virtual_number",
    "brand_name",
  ],
  [TEMPLATE_TYPE.RENEWAL_PAYMENT_SUCCESS_ADMIN]: [
    "user",
    "customer_name",
    "amount",
    "virtual_number",
    "brand_name",
  ],
  [TEMPLATE_TYPE.RENEWAL_PAYMENT_FAILED_CUSTOMER]: [
    "user",
    "virtual_number",
    "support_number",
    "support_email",
    "brand_name",
  ],
  [TEMPLATE_TYPE.RENEWAL_PAYMENT_FAILED_ADMIN]: [
    "user",
    "customer_name",
    "amount",
    "failure_reason",
    "brand_name",
  ],
  [TEMPLATE_TYPE.OFFLINE_PAYMENT_APPROVED_CUSTOMER]: [
    "user",
    "virtual_number",
    "brand_name",
  ],
  [TEMPLATE_TYPE.OFFLINE_PAYMENT_APPROVED_ADMIN]: [
    "user",
    "customer_name",
    "virtual_number",
    "amount",
    "brand_name",
  ],
  [TEMPLATE_TYPE.NUMBER_ACTIVATED_ADMIN]: [
    "user",
    "customer_name",
    "virtual_number",
    "forward_number",
    "start_date",
    "end_date",
    "brand_name",
  ],
  [TEMPLATE_TYPE.CALL_FORWARD_UPDATED_ADMIN]: [
    "user",
    "customer_name",
    "virtual_number",
    "forward_number",
    "brand_name",
  ],
  [TEMPLATE_TYPE.NUMBER_SUSPENDED_ADMIN]: [
    "user",
    "customer_name",
    "virtual_number",
    "brand_name",
  ],
  [TEMPLATE_TYPE.TELECOM_SUSPENSION_SUPER]: [
    "user",
    "virtual_number",
    "reseller_name",
    "platform_name",
  ],
};
